apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-app
  labels:
    app: train-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: train-app

  template:
    metadata:
      labels:
        app: train-app

    spec:
      containers:
      - name: train-app

        image: 736722722555.dkr.ecr.ap-south-1.amazonaws.com/hackathon-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
